### ISSUE TITLE
Script isn't working!

### ISSUE THREAD

**Issue by utkarshgpta** [UtkarshGpta/bing-desktop-wallpaper-changer#28]
I am getting the following error when I run the script manually.

`Traceback (most recent call last):
  File "./main.py", line 21, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
`

**Comment by utkarshgpta** [comment]
Read this documentation on libnotify if you get the same errors.
I installed the development packages too, it finally got working. Helped me out.
[http://www.devdungeon.com/content/desktop-notifications-python-libnotify](url)
