### ISSUE TITLE
Namespace Notify not available

### ISSUE THREAD

**Issue by vkkodali** [UtkarshGpta/bing-desktop-wallpaper-changer#29]
I am seeing the following error: 

```
$ python main.py 
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```

A fix/solution would be much appreciated. Thanks.

**Comment by utkarshgpta** [comment]
@vkkodali Have a look at this issue, I had the same. #28

**Comment by vkkodali** [comment]
Thanks, it works now.
